# cython: cdivision = True

from .graph cimport Graph, node_t
from .libcpp.random cimport bernoulli_distribution, mt19937, random_device, uniform_real_distribution
from libc cimport math
from libcpp.utility cimport move
import numbers
from .util import assert_interval


cdef class RandomEngine:
    cdef mt19937 instance

    def __init__(self, seed: int = None):
        cdef random_device rd
        if seed is None:
            self.instance = mt19937(rd())
        else:
            self.instance = mt19937(seed)

    def __call__(self):
        return self.instance()


DEFAULT_RANDOM_ENGINE = RandomEngine()


cpdef RandomEngine get_random_engine(engine_seed_or_none: int = None):
    if engine_seed_or_none is None:
        return DEFAULT_RANDOM_ENGINE
    elif isinstance(engine_seed_or_none, RandomEngine):
        return engine_seed_or_none
    else:
        return RandomEngine(engine_seed_or_none)


def duplication_divergence_graph(int n, float p, float beta=0, Graph graph = None,
                                 RandomEngine random_engine = None) -> Graph:
    r"""
    Duplication divergence graph with random mutations as described by
    `Sole et al. (2002) <Sole2002>`_.

    Args:
        n: Number of nodes.
        p: Edge retention probability, i.e. the probability that a duplicated edge is retained. The
            parameter is denoted :math:`1 - \delta` in `Sole et al. (2002) <Sole2002>`_.
        beta: Scaled mutation probability such that a random connection between the duplicated node
            and any existing node is created with probability `beta / current_num_nodes`.

    Returns:
        graph: Graph generated by the duplication divergence model.

    .. Sole2002: https://doi.org/10.1142/S021952590200047X
    """
    cdef bernoulli_distribution retention_dist = bernoulli_distribution(p)
    cdef bernoulli_distribution mutation_dist
    cdef node_t new_node, random_neighbor, seed_node
    assert_interval("n", n, 2, None)
    assert_interval("p", p, 0, 1)
    assert_interval("beta", beta, 0, None)
    random_engine = get_random_engine(random_engine)

    if not graph:
        graph = Graph()
        graph.add_edge(0, 1)

    while graph.number_of_nodes() < n:
        new_node = graph.number_of_nodes()
        # Choose a random node from current graph to duplicate.
        seed_node = random_engine.instance() % new_node
        # Pick another random neighbor if this step is to include a mutation.
        random_neighbor = -1
        # Relatively cheap check to avoid constructing `bernoulli_distribution` if we don't need it.
        if beta > 0:
            mutation_dist = bernoulli_distribution(min(beta / new_node, 1))
            if mutation_dist(random_engine.instance):
                random_neighbor = random_engine.instance() % new_node
        # Duplicate links independently with the given probability.
        for neighbor in graph._adjacency_map[seed_node]:
            if retention_dist(random_engine.instance):
                graph.add_edge(new_node, neighbor)

        if random_neighbor >= 0:
            graph.add_edge(new_node, neighbor)
    return graph


# This generator is currently commented out because it behaves strangely (see TODO note below).
# def fast_gnp_random_graph(int n, float p, Graph graph = None, RandomEngine random_engine = None) \
#         -> Graph:
#     cdef uniform_real_distribution[float] uniform = uniform_real_distribution[float](0, 1)
#     cdef node_t v, w
#     assert_interval("p", p, 0, 1)
#     assert_interval("n", n, 1, None)
#     random_engine = get_random_engine(random_engine)
#
#     if not graph:
#         graph = Graph()
#     for i in range(n):
#         graph.add_node(i)
#
#     lp = math.log1p(-p)
#
#     v = 1
#     w = -1
#     while v < n:
#         # TODO: why does this behaves different from random.random and is sometimes *really* slow?
#         lr = math.log1p(-uniform(random_engine.instance))
#         w = w + 1 + <node_t>math.floor(lr / lp)
#         while w >= v and v < n:
#             w = w - v
#             v = v + 1
#         if v < n:
#             graph.add_edge(v, w)
#     return graph


def gnp_random_graph(int n, float p, Graph graph = None, RandomEngine random_engine = None):
    cdef bernoulli_distribution create_edge = bernoulli_distribution(p)
    cdef node_t u, v
    cdef bint added
    assert_interval("p", p, 0, 1)
    assert_interval("n", n, 1, None)
    random_engine = get_random_engine(random_engine)

    graph = graph or Graph()

    for u in range(n):
        graph.add_node(u)
        for v in range(u + 1, n):
            if create_edge(random_engine.instance):
                graph.add_edge(u, v)

    return graph
